"""init_helpdesk

Revision ID: 0c0805d7894d
Revises: 
Create Date: 2026-07-31 14:55:22.286014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0805d7894d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.Text(), nullable=False),
    sa.Column('categorydescription', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('categoryid')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_categoryname'), ['categoryname'], unique=True)

    op.create_table('priorities',
    sa.Column('priorityid', sa.Integer(), nullable=False),
    sa.Column('priorityname', sa.String(length=255), nullable=False),
    sa.Column('prioritylevel', sa.Integer(), nullable=False),
    sa.Column('prioritydelayhours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('priorityid')
    )
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorities_priorityname'), ['priorityname'], unique=True)

    op.create_table('roles',
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('roleid')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_rolename'), ['rolename'], unique=True)

    op.create_table('sites',
    sa.Column('siteid', sa.Integer(), nullable=False),
    sa.Column('sitename', sa.String(length=50), nullable=True),
    sa.Column('siteaddress', sa.Text(), nullable=True),
    sa.Column('sitecity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('siteid')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_sitename'), ['sitename'], unique=True)

    op.create_table('teams',
    sa.Column('teamid', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=50), nullable=True),
    sa.Column('teamdescription', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('teamid')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_teamname'), ['teamname'], unique=True)

    op.create_table('users',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('useremail', sa.String(length=120), nullable=False),
    sa.Column('userpassword', sa.String(length=255), nullable=False),
    sa.Column('userfirstname', sa.String(length=50), nullable=False),
    sa.Column('userlastname', sa.String(length=50), nullable=False),
    sa.Column('teamid', sa.Integer(), nullable=True),
    sa.Column('siteid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['siteid'], ['sites.siteid'], ),
    sa.ForeignKeyConstraint(['teamid'], ['teams.teamid'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_useremail'), ['useremail'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('equipments',
    sa.Column('equipmentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipmentname', sa.String(length=50), nullable=False),
    sa.Column('equipmenttype', sa.String(length=50), nullable=False),
    sa.Column('equipmentserial', sa.String(length=50), nullable=True),
    sa.Column('equipmentpurchasedate', sa.Date(), nullable=False),
    sa.Column('siteid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['siteid'], ['sites.siteid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('equipmentid'),
    sa.UniqueConstraint('equipmentserial')
    )
    op.create_table('knowledgearticles',
    sa.Column('articleid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('articletitle', sa.String(length=100), nullable=False),
    sa.Column('articlecontent', sa.Text(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['categoryid'], ['categories.categoryid'], ),
    sa.PrimaryKeyConstraint('articleid')
    )
    op.create_table('userroles',
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['roleid'], ['roles.roleid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('roleid', 'userid')
    )
    op.create_table('tickets',
    sa.Column('ticketid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('duedate', sa.Date(), nullable=False),
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('technicianid', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('priorityid', sa.Integer(), nullable=False),
    sa.Column('equipmentid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['categoryid'], ['categories.categoryid'], ),
    sa.ForeignKeyConstraint(['equipmentid'], ['equipments.equipmentid'], ),
    sa.ForeignKeyConstraint(['priorityid'], ['priorities.priorityid'], ),
    sa.ForeignKeyConstraint(['technicianid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('ticketid')
    )
    op.create_table('attachments',
    sa.Column('attachmentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachmentfilename', sa.String(length=255), nullable=False),
    sa.Column('attachmentpath', sa.String(length=500), nullable=False),
    sa.Column('attachmentsize', sa.Integer(), nullable=False),
    sa.Column('ticketid', sa.Integer(), nullable=False),
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], ),
    sa.PrimaryKeyConstraint('attachmentid')
    )
    op.create_table('comments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentcontent', sa.Text(), nullable=False),
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('ticketid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], ),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('satisfactionsurveys',
    sa.Column('surveyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surveyrating', sa.Integer(), nullable=False),
    sa.Column('surveycomment', sa.Text(), nullable=False),
    sa.Column('ticketid', sa.Integer(), nullable=True),
    sa.Column('clientid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['clientid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], ),
    sa.PrimaryKeyConstraint('surveyid'),
    sa.UniqueConstraint('ticketid')
    )
    op.create_table('ticketstatushistories',
    sa.Column('historyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticketid ', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('oldstatus', sa.String(length=50), nullable=False),
    sa.Column('newstatus', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticketid '], ['tickets.ticketid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('historyid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketstatushistories')
    op.drop_table('satisfactionsurveys')
    op.drop_table('comments')
    op.drop_table('attachments')
    op.drop_table('tickets')
    op.drop_table('userroles')
    op.drop_table('knowledgearticles')
    op.drop_table('equipments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_useremail'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_teamname'))

    op.drop_table('teams')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_sitename'))

    op.drop_table('sites')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_rolename'))

    op.drop_table('roles')
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorities_priorityname'))

    op.drop_table('priorities')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_categoryname'))

    op.drop_table('categories')
    # ### end Alembic commands ###
